<?php
$GLOBALS['ACTION_RESTORE'] = "RESTORE_PASSWORD";
$GLOBALS['ACTION_ACTIVATE'] = "ACTIVATE_ACCOUNT";
$GLOBALS['ACTION_UPDATE_PASS'] = "ACTION_UPDATE_PASS";
$GLOBALS['ACTION_UPDATE_EMAIL'] = "ACTION_UPDATE_EMAIL";
$GLOBALS['ACTION_UPDATE_USERNAME'] = "ACTION_UPDATE_USERNAME";
$GLOBALS['ACTION_DELETE_ACCOUNT'] = "ACTION_DELETE_ACCOUNT";